"""fix donation create_date default

Revision ID: 94dc45e42b64
Revises: 84fe365340f6
Create Date: 2025-11-08 08:13:12.898946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dc45e42b64'
down_revision = '84fe365340f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donation', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('donation', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('donation', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donation', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('donation', 'invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
